global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'agent_manager'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agent-manager:8000']

  - job_name: 'agent_runtime'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agent-runtime:8001']

  - job_name: 'api_gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
